resources:
  - name: gitstuff
    type: git
    source:
      uri: https://github.com/ojasaar/concourse-test.git
      branch: main

jobs:
  - name: produce-diffs
    plan:
      - get: gitstuff
      - in_parallel:
        - task: cluster1
          file: gitstuff/diff_task.yml
          output_mapping: 
            diff_output: main04_fra_staging_diff
          params:
            CLUSTER_NAME: main04-fra-staging
        - task: cluster2
          file: gitstuff/diff_task.yml
          output_mapping: 
            diff_output: main03_fra_staging_diff
          params:
            CLUSTER_NAME: main3-fra-staging
      - task: read
        config:
          platform: linux
          image_resource:
            source:
              repository: ubuntu
            type: docker-image
          inputs:
            - name: main04_fra_staging_diff
            - name: main03_fra_staging_diff
          run:
            path: bash
            args:
            - -ec
            - |
              cat ./main04_fra_staging_diff/diff.md
              cat ./main03_fra_staging_diff/diff.md

