resource_types:
- name: git-ubuntu
  type: registry-image
  source: 
    repository: docker.io/concourse/git-resource
    tag: ubuntu

resources:
  - name: gitstuff
    type: git-ubuntu
    source:
      uri: https://github.com/ojasaar/concourse-test.git
      branch: main

jobs:
  - name: produce-diffs
    plan:
      - get: gitstuff
      - in_parallel:
        - task: cluster1
          file: gitstuff/diff_task.yml
          output_mapping: 
            diff_output: main04_fra_staging_diff
          params:
            CLUSTER_NAME: main04-fra-staging
      - task: read
        config:
          platform: linux
          image_resource:
            source:
              repository: ubuntu
              type: registry-image
          inputs:
            - name: main04_fra_staging_diff
          run:
            path: /bin/bash
            args:
              - |
                cat main04_fra_staging_diff/diff.md

